esphome:
  name: main-sensors
  friendly_name: Camper Sensors

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "lay6SIF7JfXEWFqlsV/gGo0Zjvx9sP3cjVbWHuOMoLQ="

ota:
  - platform: esphome
    password: "de4d2d73b2a330717843abfd6a06254a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Main-Sensors Fallback Hotspot"
    password: "Mpko0dbl3ETJ"

captive_portal:

sensor:
- platform: dht
  id: camper_temp
  pin: GPIO2
  temperature:
    name: "Camper Temperature"
  humidity:
    name: "Camper Humidity"
  update_interval: 5s
    