esphome:
  name: camper-sensors2
  friendly_name: camper-sensors2

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "4oZ1DNLfgXO8aEDH5nKXANdxhVny72LwwqGjBtnYoBo="

ota:
  - platform: esphome
    password: "c8c3e69f905f209e827d6be3855fcc6c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Camper-Sensors2 Fallback Hotspot"
    password: "ZSEFremxoXaM"

captive_portal:

number:
  - platform: template
    id: heart_beat2
    name: "Heart Beat2"
    internal: False
    min_value: 0
    max_value: 9
    step: 1
    update_interval: 10s
    #optimistic: True #helps showing the entity in HA UI
    lambda: 'return millis();'
    set_action: #empty, required
      then:

sensor:
- platform: uptime
  name: "Up Time"
  id: uptime_counter
  internal: false
  update_interval: 10s
  accuracy_decimals: 0
    
- platform: template
  id: heart_beat
  name: "Heart Beat"
  internal: false
  update_interval: 15s
  lambda: 'return millis();'

- platform: dht
  id: camper_sensors
  pin: GPIO2
  temperature:
    id: "camper_temp"
    name: "Camper Temperature"
  humidity:
    id: "camper_humi"
    name: "Camper Humidity"
  update_interval: 5s
    